# config for huggingface distilbert

includes:
  - "../base.yml"

dataset:
    tokenizer:
        name: bert_tokenizer
        vocab:
            filename: null
            special_tokens:
                PAD: "[PAD]"
                UNK: "[UNK]"
                SEP: "[SEP]"
                CLS: "[CLS]"
                MASK: "[MASK]"
        tokenize_chinese_chars: false
        do_lower_case: True
        do_basic_tokenize: True
        non_split_tokens: null
        max_len: 512

pretrained:
    name: bert-base-chinese-huggingface
    force_download: false
    init_from_pretrained: true
    cache_dir: /search/data1/yyk/data/pretrained/bert
    model_path: null
    vocab_path: null
    config_path: null
    config:
        output_attentions: false
        output_hidden_states: false
        layer_norm_eps: 1e-12

    family:
        distilbert-base-uncased:
            model:
                url: "https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-tf_model.h5"
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                url: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt"
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                url: "https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-config.json"
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config
                others:
                    max_len:
                        to_replaces:
                            - dataset.tokenizer.max_len
                        value: 512
        distilbert-base-uncased-distilled-squad:
            model:
                url: "https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-distilled-squad-tf_model.h5"
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                url: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased-vocab.txt"
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                url: "https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-distilled-squad-config.json"
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config
                others:
                    max_len:
                        to_replaces:
                            - dataset.tokenizer.max_len
                        value: 512