includes:
  - "../pretrain/bert_wwm.yml"

model_name: bert_for_role_ner_v2

model_attributes:
    hidden_dropout_prob: 0.5
    initializer_range: 0.02
    hidden_size: 1024
    pos_emb_size: 768
    attention_probs_dropout_prob: 0.5
    num_attention_heads: 4

training:
  learning_rate: 3e-5
  max_epochs: 30
  batch_size: 16
  callbacks:
    # callback name
    early_stopping:
      switch: true
      config:
        patience: 2

dataset:
  name: "lstc_2020/DuEE_role"
  data_dir: "./data"
  transformer: "lstc_2020/DuEE_role"

  source:
    train: "train"
    validation: "validation[:50%]"
    test: "validation[-50%:]"

  tokenizer:
    max_len: 150

  inputs:
    - name: input_ids
      column: input_ids
      type: LIST_OF_INT
      max_len: 150
    - name: token_type_ids
      column: token_type_ids
      type: LIST_OF_INT
      max_len: 150
    - name: attention_mask
      column: attention_mask
      type: LIST_OF_INT
      max_len: 150
    - name: label_mask
      column: label_mask
      type: LIST_OF_INT

  outputs:
    - name: output_1
      column: labels
      type: LIST_OF_CLASSLABEL
      task: NER
      num: 0
      labels:
        url: "https://ai.baidu.com/file/9C92719AF96D4DDB96477BFBE1435262"
        name: "duee_role_ner_labels"
      loss:
#        name: myself_crf_loss
#        name: cce_dce_loss
#        config:
#          from_logits: true
#          label_num: 243
#          seq_len: 150
#          name: "val_loss"
        name: sparse_categorical_crossentropy
        config:
          from_logits: true
      metrics:
        - name: sparse_categorical_accuracy

pretrained:
    name: chinese_roberta_wwm_large_ext
    init_from_pretrained: true


