includes:
  - "../pretrain/bert_wwm.yml"

model_name: bert_for_event_extract

model_attributes:
    hidden_dropout_prob: 0.5
    initializer_range: 0.02
    hidden_size: 1024
    pos_emb_size: 768
    attention_probs_dropout_prob: 0.5
    num_attention_heads: 4

training:
  learning_rate: 3e-5
  max_epochs: 30
  batch_size: 32
  callbacks:
    # callback name
    early_stopping:
      switch: true
      config:
        patience: 2

dataset:
  name: "lstc_2020/DuEE_role"
  data_dir: "./data"
  transformer: "lstc_2020/DuEE_joint"

  source:
    train: "train"
    validation: "validation[:50%]"
    test: "validation[-50%:]"

  tokenizer:
    max_len: 150

  inputs:
    - name: input_ids
      column: input_ids
      type: LIST_OF_INT
      max_len: 150
    - name: token_type_ids
      column: token_type_ids
      type: LIST_OF_INT
      max_len: 150
    - name: attention_mask
      column: attention_mask
      type: LIST_OF_INT
      max_len: 150

  outputs:
    - name: output_1
      column: trigger_labels
      type: LIST_OF_CLASSLABEL
      task: NER
      weight: 1.0
      num: 0
      labels:
        url: "https://ai.baidu.com/file/9C92719AF96D4DDB96477BFBE1435262"
        name: "duee_trigger_ner_labels"
      loss:
#        name: sparse_categorical_crossentropy
        name: sparse_softmax_focal_crossentropy
        config:
          from_logits: true
          reduction: "sum"
      metrics:
        - name: sparse_categorical_accuracy
    - name: output_2
      column: role_labels
      type: LIST_OF_CLASSLABEL
      task: NER
      weight: 1.0
      num: 0
      labels:
        url: "https://ai.baidu.com/file/9C92719AF96D4DDB96477BFBE1435262"
        name: "duee_role_ner_labels"
      loss:
#        name: sparse_categorical_crossentropy
        name: sparse_softmax_focal_crossentropy
        config:
          from_logits: true
          reduction: "sum"
      metrics:
        - name: sparse_categorical_accuracy
#    - name: output_3
#      column: relation_labels
#      type: LIST_OF_INT
#      num: 22500
#      weight: 1.0
#      loss:
##        name: sigmoid_cross_entropy
#        name: sigmoid_focal_crossentropy
#        config:
#          from_logits: true
#          reduction: "sum"
#      metrics:
#        - name: categorical_accuracy
##        - name: hamming_loss
##          config:
##            mode: "multilabel"

pretrained:
    name: chinese_roberta_wwm_ext
    init_from_pretrained: true


