includes:
  - "../pretrain/bert_wwm.yml"

model_name: bert_for_ner

model_attributes:
    hidden_dropout_prob: 0.5
    initializer_range: 0.02
    hidden_size: 1024

training:
  learning_rate: 3e-4
  max_epochs: 30
  batch_size: 8
  callbacks:
    # callback name
    early_stopping:
      switch: true
      config:
        patience: 2

dataset:
  name: lstc_2020/DuEE_trigger
  data_dir: "./data"
  transformer: "lstc_2020/DuEE_trigger"

  source:
    train: "train"
    validation: "validation[:50%]"
    test: "validation[-50%:]"

  tokenizer:
    max_len: 150

  inputs:
    - name: input_ids
      column: input_ids
      type: LIST_OF_INT
      max_len: 150
    - name: token_type_ids
      column: token_type_ids
      type: LIST_OF_INT
      max_len: 150
    - name: attention_mask
      column: attention_mask
      type: LIST_OF_INT
      max_len: 150

  outputs:
    - name: output_1
      column: ner_labels
      type: LIST_OF_CLASSLABEL
      task: NER
      num: 0
      labels:
        url: "https://ai.baidu.com/file/9C92719AF96D4DDB96477BFBE1435262"
        name: "duee_trigger_ner_labels"
      loss:
#        name: sparse_categorical_crossentropy
        name: myself_crf_loss
#        config:
#          from_logits: true
#          reduction: "sum"
      metrics:
        - name: sparse_categorical_accuracy
#    - name: output_2
#      column: event_labels
#      type: LIST_OF_INT
#      num: 0
#      weight: 0.5
#      labels:
#        url: "https://ai.baidu.com/file/9C92719AF96D4DDB96477BFBE1435262"
#        name: "duee_event_type_labels"
#      loss:
#        name: sigmoid_focal_crossentropy
#        config:
#          from_logits: true
#          reduction: "sum"
#      metrics:
#        - name: categorical_accuracy

pretrained:
    name: chinese_roberta_wwm_large_ext
    init_from_pretrained: true


