# config for xlnet chinese
includes:
  - "../base.yml"

dataset:
    tokenizer:
        name: xlnet_tokenizer
        vocab:
            filename: null
            special_tokens:
                PAD: "<pad>"
                UNK: "<unk>"
                SEP: "<sep>"
                CLS: "<cls>"
                MASK: "<mask>"
                EOD: "<eod>"
                EOP: "<eop>"
        tokenize_chinese_chars: True
        do_lower_case: True
        do_basic_tokenize: True
        non_split_tokens: null
        max_len: 512

pretrained:
    norm_name: xlnet
    name: chinese_xlnet_base
    adapter: tf_huggingface_xlnet_adapter
    force_download: false
    init_from_pretrained: true
    cache_dir: /search/data1/yyk/data/pretrained/xlnet  # your path to save models
    model_path: null
    vocab_path: null
    config_path: null
    config:
        output_attentions: false
        output_hidden_states: false
        layer_norm_eps: 1e-12
        hidden_size: 1024
        attn_type: bi
        bi_data: false
        clamp_len: -1
        dropout: 0.1
        end_n_top: 5
        finetuning_task: null
        initializer_range: 0.02
        mem_len: null
        num_labels: 2
        reuse_len: null
    ref: https://github.com/ymcui/Chinese-PreTrained-XLNet
    family:
        chinese_xlnet_base:
            model:
                # your/path/to/chinese_xlnet_base
                url: /search/data1/yyk/data/pretrained/xlnet/chinese_xlnet_base
                suffix: xlnet_model.ckpt
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                # your/path/to/chinese_xlnet_base/spiece.model
                url: /search/data1/yyk/data/pretrained/xlnet/chinese_xlnet_base/spiece.model
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                # your/path/to/chinese_xlnet_base/xlnet_config.json
                url: /search/data1/yyk/data/pretrained/xlnet/chinese_xlnet_base/xlnet_config.json
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config
        chinese_xlnet_mid:
            model:
                # your/path/to/chinese_xlnet_mid
                url: /search/data1/yyk/data/pretrained/xlnet/chinese_xlnet_mid
                suffix: xlnet_model.ckpt
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                # your/path/to/chinese_xlnet_mid/spiece.model
                url: /search/data1/yyk/data/pretrained/xlnet/chinese_xlnet_mid/spiece.model
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                # your/path/to/chinese_xlnet_mid/spiece.model/xlnet_config.json
                url: /search/data1/yyk/data/pretrained/xlnet/chinese_xlnet_mid/xlnet_config.json
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config

